using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MOI.Patrol;
namespace Core
{
    public class Handler_Operations
    {
        private patrolsContext _context = new patrolsContext();

        public const int Opeartion_AddUser = 1;
        public const int Opeartion_UpdateUser = 2;
        public const int Opeartion_DeleteUser = 3;
        public const int Opeartion_AddUserRole = 4;
        public const int Opeartion_RemoveUserRole = 5;
        public const int Opeartion_AddPerson = 6;
        public const int Opeartion_UpdatePerson = 7;
        public const int Opeartion_DeletePerson = 8;
        public const int Opeartion_AddPatrolCar = 9;
        public const int Opeartion_UpdatePatrolCar = 10;
        public const int Opeartion_DeletePatrolCar = 11;
        public const int Opeartion_AddHandHeld = 12;
        public const int Opeartion_UpdateHandHeld = 13;
        public const int Opeartion_DeleteHandHeld = 14;
        public const int Opeartion_UserLogin = 15;
        public const int Opeartion_UserLogOut = 16;
        public const int Opeartion_UserUpdatePassword = 17;

        public const int Opeartion_Mapping_AddNew = 18;
        public const int Opeartion_Mapping_Remove = 19;
        public const int Opeartion_Mapping_Update = 20;
        public const int Opeartion_Mapping_CheckInPatrolAndHandHeld = 21;
        public const int Opeartion_Mapping_CheckOutPatrolAndHandHeld = 22;
        public const int Opeartion_Mapping_AhwalMappingGetAllData = 23;
        public const int Opeartion_Mapping_Ahwal_ChangePersonState = 24;

        public const int Opeartion_Mapping_Ops_ChangePersonState = 25;

        public const int Opeartion_Incidents_AddNew = 26;
        public const int Opeartion_Incidents_Modify = 27;
        public const int Opeartion_Incidents_Delete = 28;
        public const int Opeartion_Incidents_Close = 29;

        public const int Opeartion_Incidents_NewComment = 30;

        public const int Opeartion_Incidents_HandOverIncident = 31;
        public const int Opeartion_Incidents_UnHandOverIncident = 32;

        public const int Opeartion_IncidentsTypes_AddNew = 33;
        public const int Opeartion_IncidentsTypes_Edit = 34;


        public const int Opeartion_Status_Success = 1;
        public const int Opeartion_Status_Failed = 2;
        public const int Opeartion_Status_UnAuthorized = 3;
        public const int Opeartion_Status_UnKnownError = 4;
        public const int Opeartion_Status_LoginSuccess = 5;
        public const int Opeartion_Status_LoginFail = 6;
        public  bool Add_New_Operation_Log(Operationlogs ol)
        {

            try
            {

                // DataClassesDataContext db = new DataClassesDataContext(Handler_Global.connectString);
                ol.Timestamp = DateTime.Now; //Dont ever use autogenerated, it sucks and create issues
                _context.Operationlogs.Add(ol);
                _context.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {

                // MessageBox.Show(ex.Message);
            }
            return false;
        }
    }
}
